---
kind: pipeline
name: default

trigger:
  event:
    - push
    - pull_request
    - tag

clone:
  disable: true

steps:
- name: git
  pull: default
  image: plugins/git
  settings:
    depth: 0
  tags: true

- name: update-chart-index
  image: docker.io/bitpoke/build:v0.7.0
  environment:
    SSH_KEY:
      from_secret: SSH_KEY
  commands:
    - /usr/local/bin/setup-credentials-helper.sh
    - git config --global user.email "bot@bitpoke.io"
    - git config --global user.name "Bitpoke Bot"
    - git config --global push.default current
    - git remote set-url origin git@github.com:bitpoke/helm-charts.git
    - ssh-keyscan -H github.com > /etc/ssh/ssh_known_hosts
    - make index
    - make publish
  when:
    branch: master
---
kind: signature
hmac: 34c57e82ba36d4c336e682bf28832de7343d0820881d13a8ba0dc3d0ecb57631

...
